openapi: 3.0.4
info:
  title: CrushSuite Service API
  version: "1.0.0"
  description: >
    OpenAPI for the Service API namespace mounted at `/service-api`. Includes
    compliance checks, fee calculation, and event logging.
    Based on OpenAPI 3.0.4 spec.
    Reference: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.4.md
servers:
  - url: https://crush-suite-production.up.railway.app/service-api
    description: Production
  - url: https://crush-suite-staging.up.railway.app/service-api
    description: Staging

tags:
  - name: Health
  - name: Compliance
  - name: Events

paths:
  /:
    get:
      tags: [Health]
      summary: Service API root
      description: Simple health endpoint for the Service API namespace.
      responses:
        "200":
          description: Root reached successfully
          content:
            text/plain:
              schema:
                type: string
                example: success, you have hit the root of the service-api

  /compliance/prepurchase-compliance:
    post:
      tags: [Compliance]
      summary: Verify purchase compliance
      description: >
        Checks whether a proposed order is compliant and returns result,
        possible compliance fee, and optionally a `complianceKey` when valid.
      security:
        - ApiKeyAuth: []
        - ApiKeySandboxAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderCheckComplianceRequest"
      responses:
        "200":
          description: Compliance check result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderCheckComplianceResponse"
        "400":
          description: Invalid request payload
        "401":
          description: Not authorized
        "429":
          description: Too Many Requests (rate limited)
        "500":
          description: Internal server error

  /compliance/alcohol-fee:
    post:
      tags: [Compliance]
      summary: Get compliance fee products
      description: >
        Calculates alcohol compliance fees for valid orders without performing
        a full compliance validation.
      security:
        - ApiKeyAuth: []
        - ApiKeySandboxAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderCheckComplianceFeeRequest"
      responses:
        "200":
          description: Fee calculation result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderCheckComplianceFeeResponse"
        "400":
          description: Invalid request payload
        "401":
          description: Not authorized
        "429":
          description: Too Many Requests (rate limited)
        "500":
          description: Internal server error

  /compliance/compliance-event:
    post:
      tags: [Events]
      summary: Record precompliance event
      description: >
        Records a precompliance event for analytics/troubleshooting purposes.
        Intended to be best-effort; returns success message even when logging fails.
      security:
        - ApiKeyAuth: []
        - ApiKeySandboxAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PrecomplianceEvent"
      responses:
        "200":
          description: Event recorded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required: [message]
                example:
                  message: event recorded
        "401":
          description: Not authorized
        "429":
          description: Too Many Requests (rate limited)
        "500":
          description: Internal server error

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: Private API key for production/standard access.
    ApiKeySandboxAuth:
      type: apiKey
      in: header
      name: x-api-key-sandbox
      description: Sandbox API key. When present, applies sandbox context.

  schemas:
    VariantQuantity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        quantity:
          type: integer
          minimum: 1
      required: [id, quantity]

    OrderCheckComplianceAddress:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        businessName:
          type: string
        street1:
          type: string
        street2:
          type: string
        city:
          type: string
        postalCode:
          type: string
        stateCode:
          type: string
        country:
          type: string
          description: Two-letter country code
      required:
        - firstName
        - lastName
        - street1
        - city
        - postalCode
        - stateCode
        - country

    OrderCheckComplianceDOB:
      type: object
      properties:
        day:
          type: integer
          minimum: 1
          maximum: 31
        month:
          type: integer
          minimum: 1
          maximum: 12
        year:
          type: integer
          minimum: 1900
      required: [day, month, year]

    OrderCheckComplianceRequest:
      type: object
      properties:
        variants:
          type: array
          items:
            $ref: "#/components/schemas/VariantQuantity"
        billToAddress:
          $ref: "#/components/schemas/OrderCheckComplianceAddress"
        shipToAddress:
          $ref: "#/components/schemas/OrderCheckComplianceAddress"
        dob:
          $ref: "#/components/schemas/OrderCheckComplianceDOB"
        email:
          type: string
          format: email
        phoneNumber:
          type: string
        bypassKYC:
          type: boolean
          description: For development/testing purposes
      required:
        - variants
        - billToAddress
        - shipToAddress
        - dob
        - email
        - phoneNumber

    ComplianceFee:
      type: object
      description: Map of variantId to fee quantity
      additionalProperties:
        type: integer
      example:
        "12345": 2
        "67890": 1

    OrderCheckComplianceResponse:
      type: object
      properties:
        valid:
          type: boolean
        complianceFee:
          $ref: "#/components/schemas/ComplianceFee"
          nullable: true
        complianceKey:
          type: string
          nullable: true
        errors:
          type: array
          items:
            type: string
      required: [valid, complianceFee, complianceKey, errors]

    OrderCheckComplianceFeeRequest:
      type: object
      properties:
        shippingStateCode:
          type: string
        variants:
          type: array
          items:
            $ref: "#/components/schemas/VariantQuantity"
      required: [shippingStateCode, variants]

    OrderCheckComplianceFeeResponse:
      type: object
      properties:
        fee:
          $ref: "#/components/schemas/ComplianceFee"
          nullable: true
        total:
          type: number
      required: [fee, total]

    PrecomplianceEvent:
      type: object
      properties:
        sessionId:
          type: string
        eventType:
          type: string
          description: Event type identifier
        failedReason:
          type: string
        failedPayload:
          type: string
          description: JSON string
        failedUser:
          type: string
          description: JSON string
      required: [sessionId, eventType]
